### ISSUE TITLE
Engine().session() occasionally crashes

### ISSUE THREAD

**Issue by jasonhallen** [gesellkammer/csoundengine#4]
Hi Eduardo,

About one out of 100 times that I run csoundengine my program crashes and gives me this error:

```
Traceback (most recent call last):
  File "/Users/hallenj/Documents/csound/aya/aya.py", line 1922, in <module>
    main()
  File "/Users/hallenj/Documents/csound/aya/aya.py", line 1903, in main
    window = MainWindow()
             ^^^^^^^^^^^^
  File "/Users/hallenj/Documents/csound/aya/aya.py", line 63, in __init__
    self.initialize_csound()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hallenj/Documents/csound/aya/aya.py", line 126, in initialize_csound
    self.cs = CsoundThread()
              ^^^^^^^^^^^^^^
  File "/Users/hallenj/Documents/csound/aya/csoundthread.py", line 24, in __init__
    self.session = ce.Engine(nchnls=1, backend = "auhal", ksmps=64, buffersize=256, numbuffers=4, outdev="dac0", globalcode = half_sine_table).session()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hallenj/miniconda3/envs/csound/lib/python3.11/site-packages/csoundengine/engine.py", line 1829, in session
    self._session = Session(self.name)
                    ^^^^^^^^^^^^^^^^^^
  File "/Users/hallenj/miniconda3/envs/csound/lib/python3.11/site-packages/csoundengine/session.py", line 436, in __init__
    bucketSizes = [int(size) for size in bucketSizeCurve.map(numpriorities)]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hallenj/miniconda3/envs/csound/lib/python3.11/site-packages/csoundengine/session.py", line 436, in <listcomp>
    bucketSizes = [int(size) for size in bucketSizeCurve.map(numpriorities)]
                   ^^^^^^^^^
ValueError: cannot convert float NaN to integer
Exiting python, closing all active engines
... stopping engine0
```

Any idea why this is happening?

Thanks,
Jason

**Comment by gesellkammer** [comment]
This should be fixed by now
